
worker_processes 1;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;

    server {
        listen 30081;
        client_max_body_size 100m;
        location / {
            proxy_pass http://172.18.0.3:30081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
        }
    }

    server {
        listen 30091;
        location / {
            proxy_pass http://172.18.0.3:30091;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 30900;
        client_max_body_size 10m;
        location / {
            proxy_pass http://172.18.0.3:30900;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
        }
    }

    server {
        listen 30901;
        location / {
            proxy_pass http://172.18.0.3:30901;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
        }
    }

    # ArgoCD UI (sandbox)
    server {
        listen 30443;
        client_max_body_size 100m;
        location / {
            proxy_pass http://172.18.0.3:30443;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_read_timeout 300s;
        }
    }
}

stream {
    server { listen 30082; proxy_pass 172.18.0.3:30082; }
    server { listen 30083; proxy_pass 172.18.0.3:30083; }
    server { listen 30084; proxy_pass 172.18.0.3:30084; }
    server { listen 30085; proxy_pass 172.18.0.3:30085; }
    server { listen 30086; proxy_pass 172.18.0.3:30086; }
    server { listen 30087; proxy_pass 172.18.0.3:30087; }
    server { listen 30088; proxy_pass 172.18.0.3:30088; }
    server { listen 30089; proxy_pass 172.18.0.3:30089; }
    server { listen 30090; proxy_pass 172.18.0.3:30090; }
    server { listen 30825; proxy_pass 172.18.0.3:30825; }
    server { listen 30826; proxy_pass 172.18.0.3:30826; }
    server { listen 30827; proxy_pass 172.18.0.3:30827; }
    server { listen 30828; proxy_pass 172.18.0.3:30828; }
    server { listen 30829; proxy_pass 172.18.0.3:30829; }
    server { listen 30830; proxy_pass 172.18.0.3:30830; }
}
