-- Migration 004: contact + lark_bot 表
-- Date: 2026-04-21

-- 通知人（Lark 艾特专用，跟 account 分开）
CREATE TABLE IF NOT EXISTS contact (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  lark_id VARCHAR(128) NOT NULL DEFAULT '',
  remark VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Lark 机器人（多个 webhook）
CREATE TABLE IF NOT EXISTS lark_bot (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  webhook VARCHAR(512) NOT NULL,
  secret VARCHAR(256) NOT NULL DEFAULT '',
  description VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- project_env 选一个 lark_bot
ALTER TABLE project_env ADD COLUMN lark_bot_id BIGINT NULL DEFAULT NULL;
