-- MCP 只读服务的访问 token（AI 客户端用它连 CMDB MCP）。单行。
CREATE TABLE IF NOT EXISTS mcp_config (
  id         INT PRIMARY KEY DEFAULT 1,
  token      VARCHAR(64) NOT NULL DEFAULT '',
  enabled    TINYINT NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO mcp_config (id, token) VALUES (1, '');
