apiVersion: v1
kind: Secret
metadata:
  name: devops-minio-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  root-user: {{ .Values.rootUser | quote }}
  root-password: {{ .Values.rootPassword | quote }}
