apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsplatform-deploy-frontend
  namespace: opsplatform
spec:
  replicas: 1
  selector:
    matchLabels: { app: opsplatform-deploy-frontend }
  template:
    metadata:
      labels: { app: opsplatform-deploy-frontend }
    spec:
      containers:
        - name: frontend
          image: localhost:8070/opsplatform/opsplatform-deploy-frontend:v34
          imagePullPolicy: Always
          ports:
            - { containerPort: 80 }
          resources:
            requests: { cpu: 50m,  memory: 64Mi }
            limits:   { cpu: 200m, memory: 128Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: opsplatform-deploy-frontend
  namespace: opsplatform
spec:
  type: NodePort
  selector: { app: opsplatform-deploy-frontend }
  ports:
    - { port: 80, targetPort: 80, nodePort: 30826 }
